project:
  type: website
  output-dir: docs

website:
  favicon: favicon.png
  description: "A blog built with Quarto"
  site-url: https://shrivastava95.github.io/blog-quarto/about.html # you must change this appropriately for RSS feeds to work properly
  title: "Ishaan's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shrivastava95
      - icon: twitter
        href: https://twitter.com/avatsavirhs
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css


metadata-files:
  - drafts.yml


